/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanagrafica;

import com.javacomp.procesosdeventa.Administrador;
import com.javacomp.procesosdeventa.Direccion;
import com.javacomp.procesosdeventa.Particular;
import com.javacomp.procesosdeventa.Tarjeta;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static ventanagrafica.Metodos.admins;
import static ventanagrafica.Metodos.empresas;
import static ventanagrafica.Metodos.particulares;

/**
 *
 * @author Héctor Valverde
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        DatosAdmin = new javax.swing.JFrame();
        datosAdmin = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        NuevoAdmin = new javax.swing.JFrame();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        datosEmpresa = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        DatosPart = new javax.swing.JFrame();
        datosParticular = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        DatosEmp = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(521, 305));

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Administradores");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Particulares");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Empresas");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultar:");

        jButton1.setText("Ver datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(modelo);
        jScrollPane1.setViewportView(jList1);

        jButton7.setText("Añadir admin");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        DatosAdmin.setResizable(false);
        DatosAdmin.setSize(new java.awt.Dimension(233, 193));

        jLabel6.setText("Correo:");

        jLabel7.setText("Clave:");

        jButton9.setText("Regresar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Guardar cambios");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosAdminLayout = new javax.swing.GroupLayout(datosAdmin);
        datosAdmin.setLayout(datosAdminLayout);
        datosAdminLayout.setHorizontalGroup(
            datosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosAdminLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(datosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosAdminLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addComponent(jTextField4)
                    .addComponent(jTextField3))
                .addGap(16, 16, 16))
        );
        datosAdminLayout.setVerticalGroup(
            datosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosAdminLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        javax.swing.GroupLayout DatosAdminLayout = new javax.swing.GroupLayout(DatosAdmin.getContentPane());
        DatosAdmin.getContentPane().setLayout(DatosAdminLayout);
        DatosAdminLayout.setHorizontalGroup(
            DatosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DatosAdminLayout.setVerticalGroup(
            DatosAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        NuevoAdmin.setTitle("Añadir administrador");
        NuevoAdmin.setResizable(false);
        NuevoAdmin.setSize(new java.awt.Dimension(212, 223));

        jLabel2.setText("Correo electrónico:");

        jLabel5.setText("Contraseña:");

        jButton8.setText("Crear administrador");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NuevoAdminLayout = new javax.swing.GroupLayout(NuevoAdmin.getContentPane());
        NuevoAdmin.getContentPane().setLayout(NuevoAdminLayout);
        NuevoAdminLayout.setHorizontalGroup(
            NuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoAdminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(NuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        NuevoAdminLayout.setVerticalGroup(
            NuevoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevoAdminLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout datosEmpresaLayout = new javax.swing.GroupLayout(datosEmpresa);
        datosEmpresa.setLayout(datosEmpresaLayout);
        datosEmpresaLayout.setHorizontalGroup(
            datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        datosEmpresaLayout.setVerticalGroup(
            datosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        DatosPart.setResizable(false);
        DatosPart.setSize(new java.awt.Dimension(543, 364));

        jLabel8.setText("Nombre:");

        jLabel9.setText("Correo:");

        jLabel10.setText("Clave:");

        jLabel11.setText("DNI:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Teléfono:");

        jLabel13.setText("Datos de la tarjeta:");

        jLabel14.setText("Datos de la dirección:");

        jLabel15.setText("Nombre del titular");

        jLabel16.setText("Número de tarjeta");

        jLabel17.setText("Fecha de caducidad");

        jLabel18.setText("Calle");

        jLabel19.setText("Número");

        jLabel20.setText("Código postal");

        jLabel21.setText("Ciudad");

        jButton11.setText("Guardar datos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Regresar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datosParticularLayout = new javax.swing.GroupLayout(datosParticular);
        datosParticular.setLayout(datosParticularLayout);
        datosParticularLayout.setHorizontalGroup(
            datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosParticularLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(datosParticularLayout.createSequentialGroup()
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15)
                            .addComponent(jFormattedTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(54, 54, 54))
                    .addGroup(datosParticularLayout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addGap(29, 29, 29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datosParticularLayout.setVerticalGroup(
            datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosParticularLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosParticularLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosParticularLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addGap(38, 38, 38)
                .addGroup(datosParticularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout DatosPartLayout = new javax.swing.GroupLayout(DatosPart.getContentPane());
        DatosPart.getContentPane().setLayout(DatosPartLayout);
        DatosPartLayout.setHorizontalGroup(
            DatosPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(DatosPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DatosPartLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(datosParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DatosPartLayout.setVerticalGroup(
            DatosPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(DatosPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DatosPartLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(datosParticular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout DatosEmpLayout = new javax.swing.GroupLayout(DatosEmp.getContentPane());
        DatosEmp.getContentPane().setLayout(DatosEmpLayout);
        DatosEmpLayout.setHorizontalGroup(
            DatosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DatosEmpLayout.setVerticalGroup(
            DatosEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración de JavaComp");
        setResizable(false);

        jLabel3.setText("Bienvenido a la ventana de administración de JavaComp");

        jLabel4.setText("Por favor, seleccione la operación a realizar:");

        jButton2.setText("Consulta de usuarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Consulta de productos");

        jButton4.setText("Consulta de ventas realizadas");

        jButton6.setText("Volver al inicio de sesión");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(45, 45, 45)
                .addComponent(jButton6)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    DateTimeFormatter formato = DateTimeFormatter.ofPattern("d/M/yyyy");
    DefaultListModel<String> modelo = new DefaultListModel<>();
    String tipoUsuario = "";
    int indiceLista = -1;
    Runnable error =
            (Runnable)Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.default");
            
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrame1.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        tipoUsuario = "Administrador";
        modelo.removeAllElements();
        for (int i = 0; i < admins.size(); i++) {
            modelo.addElement(admins.get(i).getCorreo());
        }
        jList1.setModel(modelo);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        indiceLista = jList1.getSelectedIndex();
        if (indiceLista == -1) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Seleccione un usuario.", 
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            if ("Administrador".equals(tipoUsuario)) {
                DatosAdmin.setLocationRelativeTo(null);
                jTextField3.setText(admins.get(indiceLista).getCorreo());
                jTextField4.setText(admins.get(indiceLista).getClave());
                DatosAdmin.setVisible(true);
            } else if ("Particular".equals(tipoUsuario)) {
                DatosPart.setLocationRelativeTo(null);
                jTextField14.setText(particulares.get(indiceLista).getDir().getCodigoPostal());
                jTextField15.setText(particulares.get(indiceLista).getDir().getCiudad());
                jTextField5.setText(particulares.get(indiceLista).getNombre());
                jTextField6.setText(particulares.get(indiceLista).getCorreo());
                jTextField7.setText(particulares.get(indiceLista).getClave());
                jTextField8.setText(particulares.get(indiceLista).getDNI());
                jFormattedTextField1.setText(particulares.get(indiceLista).getNumeroTelf());
                jTextField9.setText(particulares.get(indiceLista).getTarjetaCredito().getNombre());
                jTextField10.setText(particulares.get(indiceLista).getTarjetaCredito().getNumeroTarjeta());
                jTextField11.setText(particulares.get(indiceLista).getTarjetaCredito().getFechaCaducidad().format(formato));
                jTextField12.setText(particulares.get(indiceLista).getDir().getCalle());
                jFormattedTextField2.setText(String.valueOf(particulares.get(indiceLista).getDir().getNumero()));
                DatosPart.setVisible(true);
            } else if ("Empresa".equals(tipoUsuario)) {
                DatosEmp.setLocationRelativeTo(null);
                DatosEmp.setVisible(true);
            } else {
                if(error != null) error.run();
                JOptionPane.showMessageDialog(null, "Seleccione un tipo de usuario.", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        tipoUsuario = "Particular";
        modelo.removeAllElements();
        for (int i = 0; i < particulares.size(); i++) {
            modelo.addElement(particulares.get(i).getNombre());
        }
        jList1.setModel(modelo);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        tipoUsuario = "Empresa";
        modelo.removeAllElements();
        for (int i = 0; i < empresas.size(); i++) {
            modelo.addElement(empresas.get(i).getNombre());
        }
        jList1.setModel(modelo);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        NuevoAdmin.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String correo = jTextField1.getText();
        String clave = jTextField2.getText();
        if (correo.isEmpty() == true) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduce un correo", "Error"
            ,JOptionPane.WARNING_MESSAGE);
        } else if (clave.isEmpty() == true) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduce una clave", "Error"
            ,JOptionPane.WARNING_MESSAGE);
        } else {
            Administrador nuevoAdmin = new Administrador(correo, clave);
            admins.add(nuevoAdmin);
            Metodos.guardarDatos();
            JOptionPane.showMessageDialog(null, "Se ha añadido un administrador", "Éxito"
                ,JOptionPane.INFORMATION_MESSAGE);
            NuevoAdmin.setVisible(false);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (jTextField3.getText().isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduce un correo", "Error"
            ,JOptionPane.WARNING_MESSAGE);
        } else if (jTextField4.getText().isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduce una clave", "Error"
            ,JOptionPane.WARNING_MESSAGE);
        } else {
            Administrador nuevoAdmin = new Administrador(jTextField3.getText(), jTextField4.getText());
            admins.set(indiceLista, nuevoAdmin);
            Metodos.guardarDatos();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String nombre = jTextField5.getText();
        String correo = jTextField6.getText();
        String clave = jTextField7.getText();
        String dni = jTextField8.getText();
        String telefono = jFormattedTextField1.getText();
        String nombreT = jTextField9.getText();
        String numeroT = jTextField10.getText();
        String fechaTt = jTextField11.getText();
        String calleD = jTextField12.getText();
        String numeroDt = jFormattedTextField2.getText();
        String codigoPostalD = jTextField14.getText();
        String ciudadD = jTextField15.getText();
        int numeroD = -1;
        Direccion direccion = new Direccion("", -1, "direccionvacia", "");
        LocalDate fechaVacia = LocalDate.parse("1/1/1970", formato);
        Tarjeta tarjeta = new Tarjeta("","", fechaVacia);
        Runnable error =
            (Runnable)Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.default");
        /** se forma la dirección si existen datos**/
        if ((calleD.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una calle.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if ((numeroDt.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un número de calle.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if ((codigoPostalD.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un código postal.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if ((ciudadD.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una ciudad.",
                "Error", JOptionPane.WARNING_MESSAGE);    
        } else {
            numeroD = Integer.parseInt(numeroDt);
            direccion.setCalle(calleD); 
            direccion.setNumero(numeroD); 
            direccion.setCodigoPostal(codigoPostalD); 
            direccion.setCiudad(ciudadD);
        }
        /** se forma la tarjeta si existen datos**/
       if ((nombreT.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un nombre de titular.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if ((numeroT.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un número de tarjeta.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if ((fechaTt.isEmpty())) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una fecha.",
                "Error", JOptionPane.WARNING_MESSAGE);    
        } else {
            try {
                LocalDate nuevaFecha = LocalDate.parse(fechaTt, formato);
                tarjeta.setNombre(nombreT);
                tarjeta.setNumeroTarjeta(numeroT);
                tarjeta.setFechaCaducidad(nuevaFecha);
            } catch (DateTimeParseException ex) {
                if(error != null) error.run();
                JOptionPane.showMessageDialog(null, "Introduzca una fecha en formato (DD/MM/AAAA).",
                    "Error", JOptionPane.WARNING_MESSAGE); 
            }
        }
        /**comprueba que los datos están introducidos y tira un error si no lo están**/
        if (nombre.isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un nombre.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else if (correo.isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un correo.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else if (clave.isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una contraseña.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if (telefono.isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un teléfono.",
            "Error", JOptionPane.WARNING_MESSAGE);
        } else if (dni.isEmpty()) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca un DNI.",
                "Error", JOptionPane.WARNING_MESSAGE); 
        } else if (direccion.getCodigoPostal().equals("direccionvacia")) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una dirección.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else if (tarjeta.getFechaCaducidad().equals(fechaVacia)) {
            if(error != null) error.run();
            JOptionPane.showMessageDialog(null, "Introduzca una tarjeta.",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            Particular nuevoParticular = new Particular(dni, nombre, correo, clave, tarjeta, direccion, telefono);
            particulares.set(indiceLista, nuevoParticular);
            Metodos.guardarDatos();
            JOptionPane.showMessageDialog(null, "Se ha modificado un particular.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            }                
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        DatosPart.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DatosAdmin.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DatosAdmin;
    private javax.swing.JFrame DatosEmp;
    private javax.swing.JFrame DatosPart;
    private javax.swing.JFrame NuevoAdmin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel datosAdmin;
    private javax.swing.JPanel datosEmpresa;
    private javax.swing.JPanel datosParticular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
